"""empty message

Revision ID: d477ecb271ea
Revises: f77ebbf43073
Create Date: 2019-08-08 18:55:30.345674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd477ecb271ea'
down_revision = 'f77ebbf43073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('description', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('designation', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user', sa.Column('website', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'website')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'designation')
    op.drop_column('user', 'description')
    op.drop_column('user', 'company')
    # ### end Alembic commands ###
